name: ExtensionsBukkit
version: @version@
main: net.extbukkit.main.BukkitExtensionsBukkit
load: STARTUP
authors: [TSEngineer]
description: ExtensionsBukkit is made for making "Extensions". Extensions can add new blocks, handle events and more
api-version: 1.13
