version: 2
jobs:
  build:
    docker:
      - image: circleci/java
    steps:
      - checkout
      - run: 
        name: Build
        command: ./gradlew build
      - store_artifacts:
        path: build/libs/*
